publish_to: none

name: utm_vinculacion
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_calendar_week:
    git:
      url: https://github.com/mduccc/flutter_calendar_week
      ref: 0.1.0
  flutter_local_notifications: ^9.4.0
  android_alarm_manager_plus: ^2.0.5
  data_connection_checker: ^0.3.4
  youtube_player_iframe: ^2.2.2
  shared_preferences: ^2.0.13 # Con esto se guarda informacion en cache
  flutter_speed_dial: ^5.0.0+1
  flutter_markdown: ^0.6.9+1
  cupertino_icons: ^1.0.0
  carousel_slider: ^4.0.0
  path_provider: ^2.0.9
  url_launcher: ^6.0.20
  audioplayers: ^0.20.1
  connectivity: ^3.0.6
  flutter_svg: ^1.0.3
  sqflite: ^2.0.2
  rxdart: ^0.23.1
  intl:

dev_dependencies:
  
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 
  device_preview:

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/imagenes/logo-app.png"
  adaptive_icon_background: "assets/imagenes/logo-app.png"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/imagenes/
    - assets/
    - assets/icons/
    - .env
    - lib/modules/database/database_script.sql
    - lib/modules/database/database.sql
    - lib/modules/database/update.sql
    - lib/modules/database/update03.28.22.sql
