// Generated by https://quicktype.io

import 'dart:convert';

class Comida {
  int id;
  String nombre;
  String preparacion;
  List<String> ingredientes;
  String urlImagen;

  Comida({
    this.nombre,
    this.preparacion,
    this.ingredientes,
    this.urlImagen,
  });

  Comida.fromJson(Map<String, dynamic> item){
    id = item['id'];
    nombre = item['nombre'];
    preparacion = item['preparacion'];
    ingredientes = jsonDecode(item['ingredientes'] ?? "[]");
    urlImagen = item['urlImagen'];

    ingredientes = new List<String>();
  }

  Map<String, dynamic> toJson() => {
    "nombre":nombre,
    "preparacion":preparacion,
    "ingredientes": jsonEncode(ingredientes ?? []),
    "urlImagen":urlImagen,
  };

  set agregarIngredientes(List<String> ingredientes) {
    this.ingredientes.addAll(ingredientes);
  }

  set agregarIngrediente(String ingrediente){
    this.ingredientes.add(ingrediente);
  }
}
