// Generated by https://quicktype.io

class Actividad {
  String nombre;
  String hora;
  String rutaImagen;
  bool estado;
  String icono;

  Actividad({
    this.nombre,
    this.hora,
    this.rutaImagen,
    this.estado,
    this.icono,
  });

  Actividad.fromJson(Map<String, dynamic> json){
    nombre = json['nombre'];
    hora = json['hora'];
    rutaImagen = json['rutaImagen'];
    estado = json['estado'] == 1? true: false;
    icono = json['icono'];
  }

  Map<String, dynamic> toJson()=>{
    "nombre"    : this.nombre,
    "hora"      : this.hora,
    "rutaImagen": this.rutaImagen,
    "estado"    : this.estado? 1:0,
    "icono"     : this.icono
  };

}