// Generated by https://quicktype.io

class Comida {
  int id;
  String nombre;
  String descripcion;
  String preparacion;
  String total;
  String calorias;
  String coccion;
  String comensales;
  String tipo;
  List<String> ingredientes;
  String urlImagen;
  String rutaVista;

  Comida({
    this.nombre,
    this.descripcion,
    this.preparacion,
    this.total,
    this.calorias,
    this.coccion,
    this.comensales,
    this.tipo,
    this.ingredientes,
    this.urlImagen,
    this.rutaVista,
  });

  Comida.fromJson(Map<String, dynamic> item){
    id = int.parse(item['id']);
    nombre = item['nombre'];
    descripcion = item['descripcion'];
    preparacion = item['preparacion'];
    total = item['total'];
    calorias = item['calorias'];
    coccion = item['coccion'];
    comensales = item['comensales'];
    tipo = item['tipo'];
    // ingredientes = item['ingredientes'];
    urlImagen = item['urlImagen'];
    rutaVista = item['rutaVista'];
  }

  Map<String, dynamic> toJson() => {
    "nombre":nombre,
    "descripcion":descripcion,
    "preparacion":preparacion,
    "total":total,
    "calorias":calorias,
    "coccion":coccion,
    "comensales":comensales,
    "tipo":tipo,
    // "ingredientes":ingredientes,
    "urlImagen":urlImagen,
    "rutaVista":rutaVista
  };

  set agregarIngredientes(List<String> ingredientes) {
    this.ingredientes.addAll(ingredientes);
  }

  set agregarIngrediente(String ingrediente){
    this.ingredientes.add(ingrediente);
  }
}
